name: Dependabot

on:
  pull_request_target:

jobs:
  test:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Test Code
        env: 
          WEATHERAPI: ${{ secrets.WEATHERAPI }}
          VISUALCROSSING: ${{ secrets.VISUALCROSSING }}
          AIR_MATTERS: ${{ secrets.AIR_MATTERS }}
        run: |
          go build -v ./...
          go test -v -race ./...
          cd server
          go build -v ./...

  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 5
          retry_wait_seconds: 60
          retry_on: error
          command: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
