name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Test Code
        env: 
          WEATHERAPI: ${{ secrets.WEATHERAPI }}
          VISUALCROSSING: ${{ secrets.VISUALCROSSING }}
          AIR_MATTERS: ${{ secrets.AIR_MATTERS }}
        run: |
          go build -v ./...
          go test -v -race ./...
          cd server
          go build -v ./...
          go build -v -tags webp ./...
